# Ansible Module Name - ECS
# Interface - QueryingInstancestatusPresent
# Test Case : verify query instance statusPresent parameter with Alias
# Ansible Playbook created by - Sachin J



- name: verify query instance statusPresent parameter with Alias
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
    
    
  tasks: 
   - block: 
     - name: verify query instance statusPresent parameter with Alias
       ecs: 
        access_key: '{{ aliyun_acs_access_key }}'
        secret_key: '{{ aliyun_acs_secret_access_key }}'
        acs_region: '{{ region }}'
        zone: '{{ zone }}'  
        state: '{{ queryingInstanceStatus }}'  
           
       register: result
     - debug: var=result 
          
     rescue:
      - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
     - assert:
        that:
           - "'failed' not in result"


        msg: 'Test pass FAILED !!!'
