# Ansible Module Name - ECS
# Interface - QueryingInstancestatusPresent
# Test Case : Verify playbook is generating an error when invalid page size parameter as String is provided
# Ansible Playbook created by - Sachin J



- name: Verify querying instance interface with invalid page size parameter as String
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
    
    
  tasks: 
   - block: 
     - name: Verify querying instance interface with invalid page size parameter as String
       ecs: 
        ecs_access_key: '{{ aliyun_acs_access_key }}'
        ecs_secret_key: '{{ aliyun_acs_secret_access_key }}'
        acs_region: '{{ region }}'
        
        pagesize: '{{ pageSizeAsString }}'  
        state: '{{ queryingInstanceStatus }}'
        
       register: result
     - debug: var=result 
     
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "result.changed ==  false"
         msg: Test Pass Failed!!