#Ansible Module Name -- ecs_slb_lb.py
#Test Case : create server load balancer with alias
#Ansible Playbook created by - Abha H
---
- name: create server load balancer with alias
  hosts: localhost
  connection: local
  vars_files:
     - ../../vars/alicloud-creds.yml
     - ../vars/test-environment.yml
     - ../vars/general-parameters.yml
   
  tasks:
   - pause: 
       seconds: 20
   - block: 
     - name: create server load balancer with alias
       ecs_slb_lb:
        access_key: '{{ aliyun_acs_access_key }}'
      # ecs_access_key: '{{ aliyun_acs_access_key }}'
        secret_key: '{{ aliyun_acs_secret_access_key }}'
     #  ecs_secret_key: '{{ aliyun_acs_secret_access_key }}'
        acs_region: '{{ region }}'
     #  ecs_region: '{{ region }}'
        state: '{{ status }}'
        name: '{{ SLBName }}'
        scheme: '{{ addressType }}'
        subnet_id: '{{ VSwitchId }}'
      # subnet: '{{ VSwitchId }}'
        master_zone_id: '{{ masterZone }}'
        slave_zone_id: '{{ slaveZone }}'
        bandwidth: '{{ bandwidth }}'
       # listeners: '{{ listeners }}'
       # instance_ids: '{{ instanceIds }}'
        internet_charge_type: '{{ internetChargeType }}'
        validate_certs: '{{ validateCerts }}'
        tags: '{{ tags }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_slb_result
     - debug: var=create_slb_result
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "'failed' not in create_slb_result"
         msg: 'Test pass FAILED !!!
               Playbook FAILED due to improper input values.
               REASON: {{ create_slb_result}}'
             

 
  post_tasks: 
    - name: Delete load balancer with all parameters
      ecs_slb_lb:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       status: absent
       load_balancer_id: '{{ create_slb_result.result[0].LoadBalancerId }}'
      when:
        - "create_slb_result.changed ==  True"
