#Ansible Module Name - ECS_GROUP
#Test Case : Verify Security-Group is not queried when regionId parameters is not provided
#Ansible Playbook created by - Sachin J


- name: Querying Security-Group Without regionId Parameter
  hosts: localhost
  connection: local
  gather_facts: False


  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml 
    - ../../../vars/alicloud-creds.yml
  
  
  tasks:
  
  
   - block:
   
   
     - name: Scenario 1 - Querying Security-Group Without regionId Parameter
       ecs_group:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ regionInvalid }}'  # Invalid
         state: '{{ querySGListState }}'
         
       
       register: result1
     - debug: var=result1
     
     rescue:
      - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
  
     always:
     - assert:
        that: 
           - "'failed' in result1" 
           - "'Can not find endpoint to access.' in result1.msg[0]['Error Message']" 
           
        
 